import os
env = Environment(toolpath=[os.environ['EMSCRIPTEN']+'/tools/scons/site_scons/site_tools'])
env.Append(CXXFLAGS = ['-std=c++03'])
env.Append(CLAGS = ['-fPIC','-O3'])
env.Tool('emscripten')
env.BuildLibrary = env.Library

env.Append(CXXFLAGS='-IRHVoice/src/third-party/hts_engine')

hts_engine = env.Library("hts_engine", Glob("RHVoice/src/third-party/hts_engine/*.c"))
libsonic = env.Library("sonic","RHVoice/src/third-party/sonic/sonic.c")
libmage = env.Library("mage", Glob("RHVoice/src/third-party/mage/*.cpp"))

env.Append(CXXFLAGS='-IRHVoice/src/include')
env.Append(CXXFLAGS='-IRHVoice/src/third-party/sonic')
env.Append(CXXFLAGS='-IRHVoice/src/third-party/mage')
env.Append(CXXFLAGS='-IRHVoice/src/third-party/utf8')
env.Append(CXXFLAGS='-IRHVoice/src/third-party/rapidxml')
env.Append(CXXFLAGS='-Ilibao-1.2.0/include')

src=["RHVoice/src/audio/audio.cpp","RHVoice/src/audio/libao.cpp"]
env.Append(CPPDEFINES={"WITH_LIBAO":"1"})
libRHVoice_audio=env.Library("RHVoice_audio", src)

env.Append(CPPDEFINES={"DATA_PATH":r'\"data\"',"CONFIG_PATH":r'\"config\"',"VERSION":r'\"0.6\"', "RHVOICE":"1", "PACKAGE":r'\"RHVoice\"'})
src=["RHVoice/src/core/unicode.cpp",
	 "RHVoice/src/core/io.cpp",
	 "RHVoice/src/core/path.cpp",
	 "RHVoice/src/core/fst.cpp",
	 "RHVoice/src/core/dtree.cpp",
	 "RHVoice/src/core/lts.cpp",
	 "RHVoice/src/core/item.cpp",
	 "RHVoice/src/core/relation.cpp",
	 "RHVoice/src/core/utterance.cpp",
	 "RHVoice/src/core/document.cpp",
	 "RHVoice/src/core/ini_parser.cpp",
	 "RHVoice/src/core/config.cpp",
	 "RHVoice/src/core/engine.cpp",
	 "RHVoice/src/core/params.cpp",
	 "RHVoice/src/core/phoneme_set.cpp",
	 "RHVoice/src/core/language.cpp",
	 "RHVoice/src/core/russian.cpp",
	 "RHVoice/src/core/english.cpp",
	 "RHVoice/src/core/esperanto.cpp",
	 "RHVoice/src/core/georgian.cpp",
	 "RHVoice/src/core/ukrainian.cpp",
	 "RHVoice/src/core/kyrgyz.cpp",
	 "RHVoice/src/core/tatar.cpp",
	 "RHVoice/src/core/userdict.cpp",
	 "RHVoice/src/core/voice.cpp",
	 "RHVoice/src/core/hts_engine_impl.cpp",
	 "RHVoice/src/core/std_hts_engine_impl.cpp",
	 "RHVoice/src/core/mage_hts_engine_impl.cpp",
	 "RHVoice/src/core/hts_engine_call.cpp",
	 "RHVoice/src/core/hts_label.cpp",
	 "RHVoice/src/core/hts_labeller.cpp",
	 "RHVoice/src/core/speech_processor.cpp"]

libRHVoice_core = env.Library("RHVoice_core",src)

src = [
  "test.cpp",
  "libao-1.2.0/src/.libs/libao.so",
  "RHVoice/src/third-party/hts_engine/HTS106_engine.c",
  libRHVoice_core,
  libRHVoice_audio,
  hts_engine,
  libsonic,
  libmage]

#env.Append(CXXFLAGS='-IRHVoice/src/third-party/tclap')
test = env.Program("RHVoice-test", src, LIBS=['openal'], LINKFLAGS='-std=c++03 -fPIC -O3 --preload-file config -s ALLOW_MEMORY_GROWTH=1 -s DISABLE_EXCEPTION_CATCHING=0 -s WASM=1 -s EXPORTED_FUNCTIONS=\'["_tts"]\' -s EXTRA_EXPORTED_RUNTIME_METHODS=\'["ccall"]\'')

